# 100 pytorch exercises

This is a port of 100 numpy exercises to the pytorch library.

The original is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

trA = \sum_{i=1}^n \lambda_

|A| = \prod_{i=1}^n \lambda_i

rank(A) = |\{\lambda_i :  \lambda_i \neq 0\}|

Ax = \lambda x \Rightarrow A^{-1}x = \frac{1}{\lambda}x

Let A = diag(d_1, d_2, ..., d_n). A's eigenvalues are its diagonal values.

In [2]:
import numpy as np
import torch as t

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__, np.show_config()
t.__version__

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


'1.7.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
a = np.array([1, 2, 3])
a.size

3

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
a = np.arange(10, 50, 1)

a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
a[::-1]
hint(8)

hint: array[::-1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
a = np.array([1, 2, 0, 0, 4, 0])

np.where(a != 0)
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.randn(3, 3, 3)

array([[[-0.95075439, -0.54519125, -1.86672734],
        [ 0.26420305,  0.80387197, -0.66068356],
        [ 1.16448321,  0.68760289, -0.11482188]],

       [[ 0.38204462, -0.06431752, -0.23238453],
        [ 0.30537028, -0.56481679, -0.10871618],
        [-0.98179439,  2.38105623, -0.19351338]],

       [[ 0.13930192, -1.49691737, -0.12472427],
        [-0.33040775,  0.43930054, -1.03909162],
        [ 1.33521849,  1.17587797, -0.34638634]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a = np.random.randn(10, 10)
np.max(a), a.max()
# np.min(a)

(2.8890211689250687, 2.8890211689250687)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.mean(np.random.randn(30))

0.029737567182035737

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a = np.ones((4, 4))

a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.random.randn(3, 3)

np.pad(a, pad_width=1)

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.77634376,  0.19212576,  0.96352302,  0.        ],
       [ 0.        , -0.68148876,  2.17008957,  1.57586929,  0.        ],
       [ 0.        , -2.05362657,  0.7867484 ,  1.32917883,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
0.1 * 3

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.tril([1, 2, 3, 4, 5], -1)

np.diag(1+np.arange(4), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a = np.full((8, 8), 0)

a[1::2, ::2] = 1
# a[::2, 1::2] = 1
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
np.unravel_index([100], (6, 7, 8))

(array([1]), array([5]), array([4]))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
pattern = np.array([[0, 1], [1, 0]])
np.tile(pattern, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
t = np.random.randn(5, 5)
(t - t.mean()) / t.std()

array([[-1.28390865,  0.84336596, -1.13492586,  0.20413943,  1.14626785],
       [-1.32653   ,  2.09718263, -0.94584165,  0.74561257, -0.5799029 ],
       [-0.77541972, -0.20937168,  1.89029955,  0.51147888,  0.57931225],
       [ 0.3502228 , -1.33983124, -1.12451962,  0.05220407, -0.65501747],
       [ 0.48842465,  0.26878677,  1.19980804, -1.32859345,  0.32675676]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
rgba = np.dtype([("R", np.ubyte), ("G", np.ubyte), ("B", np.ubyte), ("A", np.ubyte)])

rgba

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
a = np.random.randint(10, size=(5, 3))
b = np.random.randint(10, size=(3, 2))

np.matmul(a, b)

array([[ 93, 101],
       [ 38,  59],
       [ 36,  52],
       [ 45,  71],
       [100, 113]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
a = np.random.randint(10, size=(10,))

In [27]:
(a > 3) & (a < 8)

array([False, False, False, False,  True, False, False, False,  True,
        True])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [28]:
answer(26)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [29]:
z = np.array([1, 2, 3, 4])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
np.array([np.nan]).astype(float).astype(int)

array([-9223372036854775808])

#### 29. How to round away from zero a float array ? (★☆☆)

In [31]:
z = np.random.uniform(-10, 10, 10)

In [32]:
z, np.copysign(np.ceil(np.abs(z)), z)

(array([ 9.72276891, -8.10037458,  4.00443688, -4.94829774,  2.61690481,
        -9.39789327, -8.61374043, -4.79711615,  6.35354049,  6.314369  ]),
 array([ 10.,  -9.,   5.,  -5.,   3., -10.,  -9.,  -5.,   7.,   7.]))

#### 30. How to find common values between two arrays? (★☆☆)

In [33]:
a = np.random.randint(10, size=(5, 2))
b = np.random.randint(10, size=(5, 2))

In [34]:
# Do it in pure Python.
set(a.flatten().tolist()).intersection(set(b.flatten().tolist()))

# Do it in numpy.
np.intersect1d(a, b)

array([1, 2, 4, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
# np.seterr(**default)

np.ones(9) / 0

answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


<ipython-input-35-6feda5c102fa>:3: RuntimeWarning: divide by zero encountered in true_divide
  np.ones(9) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [36]:
np.emath.sqrt(-1)

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [37]:
np.datetime64("today") + np.timedelta64(1)

numpy.datetime64('2022-10-04')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [38]:
st = np.datetime64("2016-07")
en = np.datetime64("2016-07") + np.timedelta64(1)
np.arange(st, en, dtype='datetime64[D]')

hint(34)

hint: np.arange(dtype=datetime64['D'])


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [39]:
a = np.array([1, 2, 3, 4], dtype=np.float32)
b = np.array([1, 2, 3, 4], dtype=np.float32)
np.add(a, b, out=a)
np.multiply(a, -1/2, out=a)

a

array([-1., -2., -3., -4.], dtype=float32)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [40]:
arr = np.random.uniform(2, 9, size=(3, 3))

arr

array([[4.3127916 , 3.90501471, 2.83796576],
       [5.99603777, 6.42367795, 7.94077497],
       [6.14891135, 7.67761172, 4.56205236]])

In [41]:
# arr.astype(np.int32)
# np.floor(arr)
# np.trunc(arr)
arr % 1

array([[0.3127916 , 0.90501471, 0.83796576],
       [0.99603777, 0.42367795, 0.94077497],
       [0.14891135, 0.67761172, 0.56205236]])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [42]:
a = np.zeros((5,5))
a += np.arange(0, 5)
    
a, np.tile(np.arange(0, 5), (5, 1))

(array([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]]),
 array([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]))

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [43]:
def gen_integer():
    for _ in range(10):
        yield np.random.randint(10)

In [44]:
np.fromiter(gen_integer(), dtype=np.int32, count=-1)

array([8, 2, 9, 6, 8, 0, 0, 0, 3, 2], dtype=int32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [45]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [46]:
a = np.random.randint(30, size=(10,))

sorted(a), a

([0, 1, 3, 6, 10, 12, 15, 18, 25, 26],
 array([ 3, 12,  1, 26, 10, 18, 15,  6,  0, 25]))

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [47]:
import time
a = np.array([3, 3, 5, 1, 2, 3, 5, 9, 1])
st = time.time()
res = a.sum()
print(f"{time.time() - st}s elapsed for a.sum, {res=}")

a = np.array([3, 3, 5, 1, 2, 3, 5, 9, 1])
st = time.time()
res = np.add.reduce(a)
print(f"{time.time() - st}s elapsed for second method, {res=}")

9.703636169433594e-05s elapsed for a.sum, res=32
0.00011277198791503906s elapsed for second method, res=32


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [48]:
a = np.random.randn(10, 10)
b = np.random.randn(10, 10)
np.allclose(a, b, atol=1e-5)
np.allclose(a, a, atol=1e-5)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [49]:
Z = np.zeros(10)
Z.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [50]:
a = np.random.randint(10, size=(10, 2))
b = np.zeros_like(a)
print(a)
b[:, 0] = np.tan(a[:, 1]/a[:, 0]) # Angle.
# b[:, 1] = np.sqrt(np.sum(a**2, axis=1)) # Distance.

b

[[3 7]
 [9 1]
 [0 1]
 [3 3]
 [2 1]
 [4 3]
 [1 0]
 [9 5]
 [9 4]
 [7 5]]


<ipython-input-50-45f76850296d>:4: RuntimeWarning: divide by zero encountered in true_divide
  b[:, 0] = np.tan(a[:, 1]/a[:, 0]) # Angle.
<ipython-input-50-45f76850296d>:4: RuntimeWarning: invalid value encountered in tan
  b[:, 0] = np.tan(a[:, 1]/a[:, 0]) # Angle.


array([[                  -1,                    0],
       [                   0,                    0],
       [-9223372036854775808,                    0],
       [                   1,                    0],
       [                   0,                    0],
       [                   0,                    0],
       [                   0,                    0],
       [                   0,                    0],
       [                   0,                    0],
       [                   0,                    0]])

In [51]:
np.sum(a**2, axis=1)

array([ 58,  82,   1,  18,   5,  25,   1, 106,  97,  74])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [52]:
a = np.random.randint(100, size=(10,))
a[np.argmax(a)] = 0
a

array([ 0,  5, 65, 61, 37, 63, 44, 80, 57, 93])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [53]:
x = np.linspace(0, 1, 10, endpoint=False)
z = np.zeros((10, 10), [("x", float), ("y", float)])
z["y"], z["x"] = np.meshgrid(x, x)

z

array([[(0. , 0. ), (0. , 0.1), (0. , 0.2), (0. , 0.3), (0. , 0.4),
        (0. , 0.5), (0. , 0.6), (0. , 0.7), (0. , 0.8), (0. , 0.9)],
       [(0.1, 0. ), (0.1, 0.1), (0.1, 0.2), (0.1, 0.3), (0.1, 0.4),
        (0.1, 0.5), (0.1, 0.6), (0.1, 0.7), (0.1, 0.8), (0.1, 0.9)],
       [(0.2, 0. ), (0.2, 0.1), (0.2, 0.2), (0.2, 0.3), (0.2, 0.4),
        (0.2, 0.5), (0.2, 0.6), (0.2, 0.7), (0.2, 0.8), (0.2, 0.9)],
       [(0.3, 0. ), (0.3, 0.1), (0.3, 0.2), (0.3, 0.3), (0.3, 0.4),
        (0.3, 0.5), (0.3, 0.6), (0.3, 0.7), (0.3, 0.8), (0.3, 0.9)],
       [(0.4, 0. ), (0.4, 0.1), (0.4, 0.2), (0.4, 0.3), (0.4, 0.4),
        (0.4, 0.5), (0.4, 0.6), (0.4, 0.7), (0.4, 0.8), (0.4, 0.9)],
       [(0.5, 0. ), (0.5, 0.1), (0.5, 0.2), (0.5, 0.3), (0.5, 0.4),
        (0.5, 0.5), (0.5, 0.6), (0.5, 0.7), (0.5, 0.8), (0.5, 0.9)],
       [(0.6, 0. ), (0.6, 0.1), (0.6, 0.2), (0.6, 0.3), (0.6, 0.4),
        (0.6, 0.5), (0.6, 0.6), (0.6, 0.7), (0.6, 0.8), (0.6, 0.9)],
       [(0.7, 0. ), (0.7, 0.1), (0.7, 0.2

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [54]:
x = np.random.randint(10, size=(10))
y = np.random.randint(10, size=(10))

cauchy = np.zeros(shape=(10, 10))

for i in range(x.shape[0]):
    for j in range(y.shape[0]):
        cauchy[i, j] = 1/(x[i] - y[j])
        
cauchy, 1/np.subtract.outer(x, y)

<ipython-input-54-624a3ca32333>:8: RuntimeWarning: divide by zero encountered in long_scalars
  cauchy[i, j] = 1/(x[i] - y[j])
<ipython-input-54-624a3ca32333>:10: RuntimeWarning: divide by zero encountered in true_divide
  cauchy, 1/np.subtract.outer(x, y)


(array([[ 0.25      , -1.        , -0.25      , -0.25      ,         inf,
         -0.5       , -1.        ,  0.5       , -0.5       ,  0.33333333],
        [ 0.25      , -1.        , -0.25      , -0.25      ,         inf,
         -0.5       , -1.        ,  0.5       , -0.5       ,  0.33333333],
        [ 0.14285714,  0.5       , -1.        , -1.        ,  0.33333333,
          1.        ,  0.5       ,  0.2       ,  1.        ,  0.16666667],
        [-1.        , -0.16666667, -0.11111111, -0.11111111, -0.2       ,
         -0.14285714, -0.16666667, -0.33333333, -0.14285714, -0.5       ],
        [ 0.2       ,         inf, -0.33333333, -0.33333333,  1.        ,
         -1.        ,         inf,  0.33333333, -1.        ,  0.25      ],
        [ 1.        , -0.25      , -0.14285714, -0.14285714, -0.33333333,
         -0.2       , -0.25      , -1.        , -0.2       ,         inf],
        [-1.        , -0.16666667, -0.11111111, -0.11111111, -0.2       ,
         -0.14285714, -0.1666666

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [55]:
ii32 = np.finfo(np.float32)

ii32.bits, ii32.min, ii32.max

(32, -3.4028235e+38, 3.4028235e+38)

#### 49. How to print all the values of an array? (★★☆)

In [56]:
a = np.random.randint(10, size=(100, 100))
np.set_printoptions(threshold=5)

In [57]:
a

array([[5, 7, 9, ..., 2, 5, 9],
       [3, 6, 9, ..., 7, 8, 5],
       [4, 3, 3, ..., 7, 6, 1],
       ...,
       [9, 9, 7, ..., 0, 4, 8],
       [5, 5, 8, ..., 6, 3, 6],
       [6, 9, 5, ..., 7, 3, 8]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [58]:
x = np.random.randint(10, size=(5,))
scalar = 5
ind = (np.abs(x - scalar)).argmin()

x[ind]

7

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [59]:
colours = np.zeros((2, 2), dtype=[("pos", (float, float)), ("colour", (float, float, float))])

answer(51)

TypeError: data type not understood

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [60]:
a = np.random.randn(3, 3).astype(np.float32)
j = a.astype(np.int32)

y = a.view(np.int32)
y[:] = a
y

# Why is this true?? 

array([[ 0,  0, -1],
       [ 0,  0,  0],
       [ 0,  0, -1]], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [61]:
a = np.array([1, 2, 3, 4], dtype=np.int64)

for idx, item in np.ndenumerate(a):
    print(f"Item at idx {idx} is {item}")

Item at idx (0,) is 1
Item at idx (1,) is 2
Item at idx (2,) is 3
Item at idx (3,) is 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [62]:
# I don't understand what's required here.
answer(56)

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


#### 57. How to randomly put some value k at p random indices in a 2D array of size n? (★★☆)
### Assume p, k <= n.

In [63]:
k = 5
n = 10
p = 5
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), k)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [65]:
a = np.random.randn(10, 10)
a - a.mean(axis=1, keepdims=True)

array([[-0.61094882, -1.1222937 ,  0.97321502, ..., -0.4147422 ,
         0.27339451,  0.41684388],
       [-0.97864815,  0.18261517, -0.51099306, ..., -0.70624166,
        -1.13116193, -1.14680126],
       [ 0.7235443 ,  0.19045837, -1.08179339, ..., -0.49668685,
         0.97646704, -0.92696648],
       ...,
       [ 1.83859218,  1.20609206,  0.58724332, ..., -2.27746731,
        -0.49196681,  1.36037282],
       [ 0.64504528, -0.08659216, -1.3230566 , ..., -0.52159749,
         0.29710097, -0.15756046],
       [ 0.37300666, -0.17338961,  0.55787373, ...,  0.42826351,
         1.69602508, -0.25558617]])

#### 59. How to sort an array by the nth column? (★★☆)

In [66]:
a = np.array([[1, 9, 2], [9, 6, 1], [2, 3, 7]])
a[:, np.argsort(a)[1]]

array([[2, 9, 1],
       [1, 6, 9],
       [7, 3, 2]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [67]:
a = np.array([[1, 2, 0], [7, 3, 0], [9, 1, 0]])
a.any(axis=0)

array([ True,  True, False])

In [68]:
((a.T == 0).sum(axis=1) == a.shape[0]).any()

True

In [69]:
a = np.array([0, 0, 0])

(~a.any(axis=0)).any()

True

#### 61. Find the nearest value from a given value in an array (★★☆)

In [70]:
val = 20
arr = np.array([1, 9, 6, 8, 13, 2])

# Do something that returns the closest item in arr to val.
arr[np.argmin(np.abs(arr-val))]

13

### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

Confusing phrasing: do we mean the sum of each element in the first array with its equivalent element in the second array? Or an outer sum, where we add all the elements to all the other elements, and get out a (3, 3) array?

In [71]:
a = np.array([[1, 2, 3]])
b = np.copy(a).T
it = np.nditer([b, a, None])

for x, y, z in it:
    z[...] = x + y

np.diag(it.operands[2])

array([2, 4, 6])

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, name: str, array: np.ndarray) -> None:
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, "name", "no name")

In [ ]:
A = NamedArray("bingus", np.array([1, 2, 3]))
A.name, A[0]

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
idx = np.array([2, 3, 0, 0])
my_vector = np.array([3, 9, 1, 4, 5])

# np.put_along_axis(my_vector, idx, np.take_along_axis(my_vector, idx, axis=0), axis=0)

my_vector

In [ ]:
vals = np.bincount(idx)

In [ ]:
np.add.at(my_vector, idx, vals)

In [ ]:
my_vector += np.bincount(idx, minlength=len(my_vector))

### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
# Again, ambiguous question.
idx = np.array([3, 0, 1, 4, 1])
v = np.array([7, 8, 0, 1, 3])

np.bincount(idx), np.bincount(idx, v)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors in the array. (★★☆)

In [104]:
# Ambiguous question again; here is how to compute how many
# colours *could* be represented with RGB channels and ubytes.
ubyte = np.iinfo(np.ubyte)
(ubyte.max-ubyte.min)**3

# Given an array that's w x h x 3, how many distinct colours does it have?
x = np.array([
        [[0, 3, 31], [12, 99, 21], [17, 3, 31]],
        [[43, 3, 31], [12, 99, 21], [17, 4, 31]],
        [[43, 3, 31], [9, 99, 21], [255, 4, 31]],
      ])

# How to check if rows are unique?
len(np.unique(x.reshape((-1, 3)), axis=0))

7

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [106]:
x = np.random.randint(0, 10, (3, 3, 3, 3))

In [109]:
# Brainstorming: ufunc.reduce/ufunc.accumulate? einsum?
np.einsum("ijkl->ij", x), np.sum(x, axis=(-2, -1))

array([[27, 54, 44],
       [49, 38, 38],
       [33, 36, 20]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [116]:
# The description for this one is abysmal – I don't get what it means.
D = np.array([1, 2, 3, 4, 5, 6])
S = np.array([0, 0, 3, 4, 4, 5])

np.mean(D[S])

3.6666666666666665

In [122]:
# This is the answer; I don't know why this is the answer.
np.mean(np.bincount(S, weights=D) / np.bincount(S))

<ipython-input-122-a93a48f6aba3>:1: RuntimeWarning: invalid value encountered in true_divide
  np.mean(np.bincount(S, weights=D) / np.bincount(S))


nan

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
a = np.random.uniform(0, 15, (3, 3))
b = np.random.uniform(0, 15, (3, 3))

np.diag(a.dot(b)), np.sum(a * b.T, axis=1), np.einsum("ij,ji->i", a, b)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = a.reshape(-1, 1)
print(b.shape)
b = np.concatenate((b, np.zeros(shape=(5, 3))), axis=1)

b.reshape(-1)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
a = np.random.randint(10, size=(5, 5, 3))
b = np.random.randint(10, size=(5, 5))

# How to **element-wise** multiply the two matrices.
np.expand_dims(b, -1).shape, b[None,:,None, :,None].shape

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
a = np.random.randint(10, size=(5, 5))

print(a)

a[[0, 4]] = a[[4, 0]]

print(a)

answer(72)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [125]:
# Did not get this one.

# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [131]:
C = np.array([3, 0, 1, 0, 2])
A = []
# Want to generate the array: [0, 0, 0, 2, 4, 4]
# Method 1: building an array from a list.
for ind, el in np.ndenumerate(C):
    A.extend([ind[0] for _ in range(el)])

# Method 2: entire array + put
# A = np.array((C.sum(), 1))
# another loop here blah blah.

# Method 3: np.repeat.
np.repeat(np.array(range(len(C))), C)

array([0, 0, 0, 2, 4, 4])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [163]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
window_size = 3

# Works now: the stride arguments need to be the same as the initial array's strides.
# It differs from Pytorch here, and I don't think learning numpy's way is that useful.
np.lib.stride_tricks.as_strided(a, (len(a)-window_size+1, window_size), (8, 8))

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [150]:
def moving_average(arr, window_size=3):
    out = np.cumsum(arr, dtype=float)
    out[window_size:] = out[window_size:] - out[:-window_size]
    return out[window_size-1:] / window_size

out = np.cumsum(a, dtype=float)
out[3:] = out[3:] - out[:-3]
out[2:] / 3

array([2., 3., 4., 5., 6., 7.])

In [139]:
import torch as t
b = t.arange(1, 9, 1)
t.as_strided(b, (len(b)-window_size+1, window_size), (1, 1))

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7],
        [6, 7, 8]])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [161]:
Z = np.array([7, 3, 1, 9, 2, 6])

# One pretty inelegant solution:
# p = np.arange(0, len(Z)-2, 1)
# Z[np.stack((p, p+1, p+2)).T]

# The answer is basically the solution to 75 with as_strided.

# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [176]:
bools = np.array([True, True, False, True])
floats = np.array([3., -2., -.1, 3.2])

np.logical_not(bools, out=bools)
np.negative(floats, out=floats)

array([-3. ,  2. ,  0.1, -3.2])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [186]:
p = np.array([0, 1])
p0 = np.array([[1, 2], [-1, 1], [-3, 3]])
p1 = np.array([[1, 3], [-2, -1], [-3, 2]])

diff = p1-p0
numerator = np.abs(
        diff[:, 0] * (p0[:, 1]-np.repeat(p, [0, p0.shape[0]])) -
        diff[:, 1] * (p0[:, 0]-np.repeat(p, [p0.shape[0], 0]))
)
denominator = np.sqrt(diff[:, 0]**2 + diff[:, 1]**2)
d = numerator / denominator

d

array([1.        , 0.89442719, 3.        ])

In [185]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

distance(p0, p1, p)

array([1.        , 0.89442719, 3.        ])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [195]:
p = np.array([[0, 1], [2, 1], [-1, 3]])
p0 = np.array([[1, 2], [-1, 1], [-3, 3]])
p1 = np.array([[1, 3], [-2, -1], [-3, 2]])

# Apply distance function for all points in p.
# 1. Loop through elements and apply, store in list, list to array.
# 2. Some way of mapping x -> f(x) for x  \in array?
# 3. Vectorise the distance function itself to take in multiple p at a time.

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [207]:
# Brainstorming:
# 1. Use as_strided
# 2. Use slicing based on index of element + new shape
# 3. Something else?

from typing import Tuple, Union
def extract_subarray(initial_array: np.ndarray, element_index: Tuple[int, int], new_shape: Tuple[int, int], pad_value: Union[int, float]) -> np.ndarray:
    x, y = element_index
    new_x, new_y = x + new_shape[0], y + new_shape[1]
    assert new_x <= initial_array.shape[0] and new_y <= initial_array.shape[1]
    return initial_array[x:x+new_x, y:y+new_y]

a = np.array([[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7]])

extract_subarray(a, (0, 0), (0, 0))

# TODO: if shape is bigger than what you can extract from array, pad with value

array([], shape=(0, 0), dtype=int64)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [216]:
z = np.arange(8)
window_size = 4
k = np.lib.stride_tricks.as_strided(z, (len(z)-window_size+1, window_size), (8, 8))

k

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [ ]:
mat = t.arange(8)
t.as_strided(mat, size=(6, 3), stride=(1, 1))

#### 82. Compute a matrix rank (★★★)

In [247]:
# Last row is 2xfirst + snd
A = np.array([[1, 2, 3], [9, 1, 2], [13, 5, 8]])

# One dedicated function:
# np.linalg.matrix_rank(A)

# Using SVD:
_, singular_values, _ = np.linalg.svd(A)

np.logical_not(np.isclose(singular_values, 0)).astype(np.int).sum()

3

#### 83. How to find the most frequent value in an array?

In [ ]:
a = np.array([1, 1, 3, 3, 3, 2, 2, 2, 9, 3])

np.argmax(np.bincount(a))

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [253]:
R = np.random.rand(5, 5)

R

array([[0.11311578, 0.80025717, 0.84082329, 0.74620591, 0.05320241],
       [0.23136558, 0.91384516, 0.74247561, 0.72712306, 0.64853213],
       [0.46392192, 0.54402524, 0.58184958, 0.00739306, 0.52946765],
       [0.73827814, 0.3930424 , 0.34286046, 0.73941078, 0.96116519],
       [0.03808524, 0.60145249, 0.81150227, 0.56238468, 0.29007575]])

In [277]:
window_size = 3
new_shape = R.shape[0]-window_size+1
res = np.lib.stride_tricks.as_strided(R,
                                (new_shape, new_shape, window_size,window_size),
                                (R.strides[0],R.strides[1],R.strides[0], R.strides[1]))

In [281]:
res[1]

array([[[0.23136558, 0.91384516, 0.74247561],
        [0.46392192, 0.54402524, 0.58184958],
        [0.73827814, 0.3930424 , 0.34286046]],

       [[0.91384516, 0.74247561, 0.72712306],
        [0.54402524, 0.58184958, 0.00739306],
        [0.3930424 , 0.34286046, 0.73941078]],

       [[0.74247561, 0.72712306, 0.64853213],
        [0.58184958, 0.00739306, 0.52946765],
        [0.34286046, 0.73941078, 0.96116519]]])

In [276]:
answer(84)

# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

# Author: Jeff Luo (@Jeff1999)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [286]:
# What do you initialise a symmetric array with?
# Either the elements above or below the diagonal;
# the rest are inferred. How to do this in a neat way?

class SymmetricArray(np.ndarray):
    def __setitem__(self, key, value):
        i, j = key
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)

# Why would this assumption be correct?
# This just sets S[i, j] = S[j, i] = A[i, j] + A[j, i].
def symmetric(A):
    return np.asarray(A + A.T - np.diag(A.diagonal())).view(SymmetricArray)

In [288]:
A = np.random.randint(0, 10, (5, 5))
S = symmetric(A)
S, A

(SymmetricArray([[ 2,  6,  4,  9,  9],
                 [ 6,  6, 12, 14, 12],
                 [ 4, 12,  7,  1, 10],
                 [ 9, 14,  1,  3, 13],
                 [ 9, 12, 10, 13,  9]]),
 array([[2, 1, 4, 7, 8],
        [5, 6, 7, 6, 7],
        [0, 5, 7, 1, 6],
        [2, 8, 0, 3, 8],
        [1, 5, 4, 5, 9]]))

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [289]:
p = 10
n = 5
matrices = np.random.randint(0, 10, (p, n, n))
vectors = np.random.randint(0, 10, (p, n, 1))

In [293]:
(matrices@vectors).sum(axis=0)

array([[1150],
       [1083],
       [1013],
       [ 979],
       [1283]])

In [303]:
np.einsum("pij,pjk->ik", matrices, vectors)

array([[1150],
       [1083],
       [1013],
       [ 979],
       [1283]])

In [307]:
np.tensordot(matrices, vectors, axes=([0, 2], [0, 1]))

array([[1150],
       [1083],
       [1013],
       [ 979],
       [1283]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [354]:
A = np.random.randint(0, 10, (4, 4))
k = 2

In [355]:
A

array([[7, 9, 0, 2],
       [3, 8, 5, 0],
       [5, 2, 3, 8],
       [0, 7, 2, 9]])

In [356]:
print(A.strides)
res = np.lib.stride_tricks.as_strided(A, (4, 4, 2, 2), (32, 16, 32, 8))

(32, 8)


In [359]:
blocks = res[::k, ::k, ...].sum(axis=(-2, -1))

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
np.info(np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [361]:
p, m = 5, 10
a = np.random.randint(0, 10, (p, m))

In [ ]:
# How would this work? Every item in the first vector with every other item in all the other vectors?

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [375]:
Z = np.array([1, 2, 3, 4])
np.power(Z, 3), Z*Z*Z, np.einsum("i,i->i", np.einsum("i,i->i", Z, Z), Z)

(array([ 1,  8, 27, 64]), array([ 1,  8, 27, 64]), array([ 1,  8, 27, 64]))

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 7, 2, 3, 8])

print(f"{np.inner(a, b)=}")
print(f"{np.einsum('i, i->', a, b)=}")
print(f"{np.outer(a, b)=}")
print(f"{np.einsum('i, j->ij', a, b)=}")
print(f"{(a+b)=}")
print(f"{np.einsum('i', a, b)=}")
print(f"{(np.multiply(a, b))=}")
print(f"{np.einsum('i,i->i', a, b)=}")

In [ ]:
answer(97)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
a = np.array([[1, 5, 6], [3, 1, 2], [4, 7, 1], [6,6,0], [5.5, 5.5, 1]])
n = 12
# Only contain integers.

# Sum to n.
criterion = (a.sum(axis=1, keepdims=True) == n) & (np.all(a.astype(int) == a, axis=1)).reshape(-1, 1)

res = a[criterion.reshape(a.shape[0])]

print(res)

In [ ]:
answer(99)

In [ ]:
m = np.logical_and.reduce(np.mod(a, 1) == 0, axis=-1)
m

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)